################
#VERBOSITY
/control/verbose 1
/run/verbose 1
/event/verbose 2
/tracking/verbose 2
/LArS/gun/verbose 1

#################
#SEED
/run/random/setRandomSeed 0

##################
# isotropic emission
/LArS/gun/angtype iso

# make sure the volume below is a bit larger than the object the source will be confined to
/LArS/gun/type   Volume  
/LArS/gun/shape  Cylinder
/LArS/gun/center 0. 0. 0. cm
/LArS/gun/radius 800 mm
/LArS/gun/halfz  1200 mm

##################
# Select the volume to confine the source. For cryostat studies choose:
# InnerCryostat - for the inner vessel
# OuterCryostat - for the outer vessel
# HexapodPlatformPhysical  HexapodLegPhysical_1 HexapodLegPhysical_2 - for the Hexapod (platform and legs)

/LArS/gun/confine PMT*

##################
# particle type + energy spectrum
/LArS/gun/energytype Spectrum
/LArS/gun/energyspectrum ./macros/spectra/neutron/flat.dat
/LArS/gun/particle neutron


##################
# MC acceleration techniques for gammas. AP playground: if false it is not used
/run/forced/setVarianceReduction false

#
# Scintillation processes in the LXe
#
/Xe/detector/setLXeScintillation false

#
# Scintillation processes in the LScint (only when material selected is "Gd_LScint")
#
/Xe/detector/setGdLScintScintillation false

# Tree Filling options
/run/writeEmpty true


###################
# command to guarantee neutrons until their capture (not needed in G4 10.03+)
# /physics_engine/neutron/energyLimit 1.e-10 eV	 
# /physics_engine/neutron/timeLimit 999999999 s
