################
#VERBOSITY
/control/verbose 0
/run/verbose 0
/event/verbose 0
/tracking/verbose 2
/LArS/gun/verbose 2

#################
#SEED
/run/random/setRandomSeed 0

##################
# isotropic emission
/LArS/gun/angtype iso

# make sure the volume below is a bit larger than the object the source will be confined to
/LArS/gun/type   Volume  
/LArS/gun/shape  Cylinder

# custom confine: 
# PMT window
#/LArS/gun/center 0. 0. -71.45 mm
#/LArS/gun/radius 100 mm
#/LArS/gun/halfz 1 mm

#All of LArS
/LArS/gun/center 0. 0. 0. m
/LArS/gun/radius 0.18 m
/LArS/gun/halfz 0.26 m

##################
# Select the volume to confine the source. E.g. /LArS/gun/confine LXe*
#/LArS/gun/confine Steel_inner_cryostat_physical
#/LArS/gun/confine Vacuum_volume_physical
#/LArS/gun/confine Steel_outer_cryostat_physical
#/LArS/gun/confine Air_volume_physical
#/LArS/gun/confine LAr_physical
/LArS/gun/confine topCell_physical
/LArS/gun/confine wallCell_physical
/LArS/gun/confine bottomCell_physical
#/LArS/gun/confine supportRod_physical*
/LArS/gun/confine pmtWindow_physical
/LArS/gun/confine acrylicWindow_physical


##################
#/LArS/gun/energytype Spectrum
#/LArS/gun/energyspectrum ./macros/spectra/neutron/flat.dat
#/LArS/gun/particle gamma 
/LArS/gun/particle geantino

##################
# MC acceleration techniques for gammas. AP playground: if false it is not used
/run/forced/setVarianceReduction false

#
# Scintillation processes in the LXe
#
#/Xe/detector/setLXeScintillation false

# Tree Filling options
/run/writeEmpty true


